CREATE TABLE IF NOT EXISTS departments (
 id CHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS app_users (
 id CHAR(36) PRIMARY KEY,
 username VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL,
 enabled BOOLEAN NOT NULL, department_id CHAR(36),
 FOREIGN KEY (department_id) REFERENCES departments(id),
 CHECK (role IN ('DEPARTMENT','CUT','OPERATOR')),
 CHECK (role <> 'DEPARTMENT' OR department_id IS NOT NULL)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tickets (
 id CHAR(36) PRIMARY KEY, version BIGINT NOT NULL, payload LONGBLOB NOT NULL
) ENGINE=InnoDB;
